### ISSUE TITLE
Question: OpenVPN requirement

### ISSUE THREAD

**Issue by dmgolembiowski** [patrickaclark/gluetun-qbittorrent-port-manager#5]
Hi @patrickaclark, thank you very much for building this.
I was wondering which version of OpenVPN was tested, or alternatively which versions should be compatible with this?

**Comment by patrickaclark** [comment]
@dmgolembiowski this does not leverage OpenVPN directly.  This leverages the GlueTun http API to modify the qbittorrent port in the stack using the qbittorrent API.  

However GlueTun handles it is on that side of the house with versions, etc is transparent to this image.

**Comment by dmgolembiowski** [comment]
> @dmgolembiowski this does not leverage OpenVPN directly.  This leverages the GlueTun http API to modify the qbittorrent port in the stack using the qbittorrent API while using an OpenVPN gluetun configuration. 
> 
> However GlueTun handles it is on that side of the house with versions, etc is transparent to this image.  

Thank you!

If I'm understanding you properly, then there is no need to modify anything on this line from start.sh?  

 ```
PORT_FORWARDED=$(curl -s ${HTTP_S}://${GLUETUN_HOST}:${GLUETUN_PORT}/v1/openvpn/portforwarded | awk -F: '{gsub(/[^0-9]/,"",$2); print $2}')
```

**Comment by patrickaclark** [comment]
> > @dmgolembiowski this does not leverage OpenVPN directly.  This leverages the GlueTun http API to modify the qbittorrent port in the stack using the qbittorrent API while using an OpenVPN gluetun configuration.
> > However GlueTun handles it is on that side of the house with versions, etc is transparent to this image.
> 
> Thank you!
> 
> If I'm understanding you properly, then there is no need to modify anything on this line from start.sh?
> 
> ```
> PORT_FORWARDED=$(curl -s ${HTTP_S}://${GLUETUN_HOST}:${GLUETUN_PORT}/v1/openvpn/portforwarded | awk -F: '{gsub(/[^0-9]/,"",$2); print $2}')
> ```

Correct, this grabs the port forwarded number that is assigned from Gluetun using GlueTun's http control server API and converts the return to just  a number, assigns that to the variable, then the image uses that variable to change qBittorrent's configuaration so that you don't get stuck 'firewalled' after checking to make sure that isn't the port number already configured.   

I've only tested this with ProtonVPN as this was not a requirement when using NordVPN as their wireguard configuration was better supported, and I only ran across this issue when switching to Proton, realizing OpenVPN is a better solution, and modifying this image for my purposes.

**Comment by dmgolembiowski** [comment]
Sweet, thanks a bunch!

**Comment by patrickaclark** [comment]
> Sweet, thanks a bunch!

If there's anything you see, I'm sure you're more experienced than me in this and welcome any suggestions.  I see you have a heck of a lot more experience in a lot of coding than I do based on your profile.  This is a very small package for a very specific problem and more of me learning to kind of GitHub.
